name: Win wheel build

on:
  workflow_dispatch:
  push:
    branches:
      - win-build-wheel

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        platform: [windows-latest]
        python-version: ["3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install locally
        run: |
          python -m pip install torch==2.3.1
          python -m pip install --upgrade pip==23.3.2
          python -m pip install ninja packaging wheel
      - uses: Jimver/cuda-toolkit@v0.2.18
        id: cuda-toolkit
        with:
          cuda: '11.8.0'
      - name: Install Deps
        run: python -m pip install .
      - name: Build the wheel
        # run: |
        #   ARCHFLAGS="-arch arm64" python setup.py bdist_wheel -d dist/
        run: python setup.py bdist_wheel -d dist/
      # - name: Check the wheel
      #   run: delocate-listdeps dist/*.whl
      - run: du -h dist/*
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl